services:
  web_gui:
    build: ./WebGUI_dash
    container_name: web_gui_manager
    ports:
      - "8050:8050"
    volumes:
      # o que permite que o docker acesse outros dockers
      - /var/run/docker.sock:/var/run/docker.sock
      # Mapeia a pasta atual para que o app.py acesse os arquivos de treino
      - cybergym_data:/app
    working_dir: /app
    command: python WebGUI_dash/app.py
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # garantir acesso no app.py

volumes:
  cybergym_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD} # O Docker preenche isso com o caminho atual automaticamente
      o: bind
